### ISSUE TITLE
Sobre

### ISSUE THREAD

**Issue by rodurma** [sr2ds/Certificacao-Laravel#1]
Interessante esse repositório. Qual é a sua ideia com ele além da lista de tópicos para estudar?

**Comment by sr2ds** [comment]
@rodurma, considerei a seguinte estrutura:

 - Tema
  -- basico
  -- intermediário
  -- avançado

Para cada tema, mantermos três arquivos de texto com links de conteúdos importantes para estudar. 
Links de artigos, vídeos, etc. De preferência tudo em português.

De repente, podemos inclusive montar playslists de conteúdos em vídeos e incluir o link da sequência de aulas nos arquivos, isso facilitará para quem prefere aprender por vídeo.

São apenas ideias, o que você pensa sobre isso?

**Comment by rodurma** [comment]
Foi o que pensei que seria o projeto mesmo. Ótimo iniciativa.
