### ISSUE TITLE
Procedimentos pra certificação

### ISSUE THREAD

**Issue by Dhayllin** [sr2ds/Certificacao-Laravel#3]
Boa tarde. Aqui é Dhayllin Dev PHP e Laravel. Preciso de uma instrução, vc sabe quais os procedimentos para tirar a certificação Laravel? Qualquer coisa pode indicar alguém que tenha tira pra me auxiliar, a principal dúvida é se na compra do voucher tbm vem um treinamento, ou é como as certificações Linux, estuda só e paga o exame? Caso seja como certificação Linux vou estudar e contribuir com esse projeto.

**Comment by sr2ds** [comment]
Bom dia Dhayllin,

Para tirar a certificação Laravel você precisa fazer o pagamento do voucher e realizar a prova. Passando na prova você terá o id de certificado Laravel.

Na compra do voucher não vem o treinamento, é similar as certificações LPI mesmo, estudamos sozinhos e fazemos a prova.

Nossa idéia é simplificar o estudo com exemplos, não apenas traduzir a documentação. Estou contribuindo aos poucos na medida que posso como poderá ver nos commits.

Sua ajuda será muito bem-vinda!
Conte comigo!

**Comment by Dhayllin** [comment]
Thanks!
