### ISSUE TITLE
Andamento

### ISSUE THREAD

**Issue by me42th** [sr2ds/Certificacao-Laravel#4]
E ai cara, tirou a certificação?

**Comment by tiagobrunoBFR** [comment]
Opa bom dia,

não tirei e no momento não tenho interesse em tirar

Em qui., 21 de jan. de 2021 às 11:45, David Meth <notifications@github.com>
escreveu:

**Comment by me42th** [comment]
Poxa, e porque você desistiu?

Tou pensando em fazer, ia perguntar se poderia contribuir pro repo de vcs....

**Comment by tiagobrunoBFR** [comment]
Por conta do preço, achei um pouco caro e o mercado, acredito que não exija
tanto, não sou adm do repo, mas deve ser só mandar uns pr para os caras
analisarem

Em ter., 26 de jan. de 2021 às 13:45, David Meth <notifications@github.com>
escreveu:

**Comment by sr2ds** [comment]
@me42th, fala chará, tudo certo?

Se quiser contribuir, é só mandar um PR mesmo, como ele falou. 
A ideia do repo é servir para estudos, mesmo que não vá tirar a certificação, caso esteja estudando e, por exemplo, queira repassar as notas de cada tema de estudo para o projeto, já é uma forma de contribuir.
Além de aprender mais por estar refletindo e escrevendo sobre o que aprendeu, ainda contribui para a galera.

Eu tenho trabalhado/estudo mais com Node no último ano, então realmente não pude contribuir.

**Comment by me42th** [comment]
@sr2ds passei na prova :DDDD

**Comment by sr2ds** [comment]
> @sr2ds passei na prova :DDDD

Sensacional!!! Parabéns!
